const dbConfig = require("../config/db.config.js")
const mongoose = require("mongoose")
mongoose.Promise = global.Promise
const db = {}
db.mongoose = mongoose
db.url = dbConfig.url
db.database = dbConfig.database
db.products = require("./product.model.js")
db.carts = require("./cart.model.js")
db.users = require("./user.model.js")
db.role = require("./role.model.js")
db.ROLES = ["user", "admin", "moderator"]
module.exports = db
